# =====================================
# HomeHub Version Configuration
# =====================================

[version]

software=HomeHub Gateway

version=0.3.1-dev

mode=MQTT Gateway

[api]

version=1.0
